Issue/6 search result
cherryp1cker/cherry-picker-frontend pull request #13
Opened 2021-07-30 08:09 UTC by SEOJIN-LEE

create new branch (issue 6 - search result)

2021-07-31 13:46 UTC, cadenzah requested changes

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/ResultItem/ResultItem.js
> +import { FaRegHeart } from "react-icons/fa"; // 빈 하트
이 패키지, 설치가 안된거 같아요. `npm install` 해주세요~ (아래 라인도 마찬가지)

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/store.js
> +class SearchResult {
이 스토어에서 임시로 더미 데이터를 반환하여 컴포넌트에서 사용되는 것으로 보이는데
우리 프로젝트에서는 Redux 스토어 관련 코드는 `src/redux/modules` 안에 별도로 파일들을 정의하고 있으니, 그곳으로 이동시키는게 적절할 것 같습니다.

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/store.js
> +class SearchResult {
비록 더미이긴 하지만, Redux를 사용하는 우리 프로젝트 구조에 맞게, 리덕스 action, reducer 를 정의하는 형태로 코드를 작성하는게 좋을 것 같아요.
(지금은 퍼블리싱이 우선이니, 인터랙션과 데이터 관련 코드는 좀 미루어둬도 상관없기는 합니다)

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/SearchBar/SearchBar.scoped.scss
> +  /* Rectangle 70 */
Figma에 정의된 스타일 값들은 반응형이 고려되지 않은 값들이니, 이를 감안하여서 Figma의 스타일들을 '참고'하여 실제로 원하는 화면이 잘 만들어지는지 보고 값을 조정해나가는 것이 좋아요. 물론 그대로 써도 되는 경우라면 그대로 써도 되겠지만...

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/SearchBar/SearchBar.scoped.scss
> +  position: absolute;
현재는 position: absolute를 사용해서 절대 위치를 부여하고 있는데,
우리 앱은 반응형 디자인이 적용되어야 하니, 이를 감안하여 가로 길이 변동하여도 가운데에 정렬되도록 스타일을 구현해주세요.

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/ResultList/ResultList.js
> +import * as store from '@/components/SearchResult/store';
`<ResultList />`는 View 역할을 담당하는 컴포넌트이니, `<SearchResultContainer />`로부터 데이터를 `props`로 전달받아서 단순히 화면을 그려주는 역할만 담당하는 것이 적절해보여요.
스토어로부터 값을 받아서 데이터를 구성하는 작업은 `@/containers/SearchResultContainer />`에서 옮기는게 어떨까 싶습니다.

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/ResultList/ResultList.js
> +    const [resultItemList, setResultItemList] = useState([]);
`<SearchResultList />`에 사용되는 데이터는 그 값이 수정되는 경우가 없을 것 같은데 (단순 목록을 보여주는 용도이므로), `<ResultItem>` 컴포넌트들을 굳이 state를 별도 저장할 필요는 없는거같아요.

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/ResultList/ResultList.js
> +    }, [refresh])
스토어 데이터가 바뀌지 않는다면 딱 한번만 데이터를 준비하는 로직은 좋은 것 같습니다.

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/ResultItem/ResultItem.js
> +import { FaRegHeart } from "react-icons/fa"; // 빈 하트
아, 아직 작업중이신 내용이군요

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/index.js
> +export default SearchResult;
이 파일은 사용되지 않는 걸로 보이는데, 제거해도 될 것 같아요.

2021-07-31 13:46 UTC, cadenzah commented on src/components/SearchResult/index.js
> +import SearchResult from '../../pages/SearchResult';
참고로, 여기 적어주신 것처럼 상대 경로의 중첩이 많이 이루어지는 경우에, 가독성이 떨어지고 휴먼 에러의 발생 소지가 있기 때문에, 이전에 설명드렸던 것처럼 `@`를 사용하여 경로를 표현하는 것을 권장합니다.
지금은 2번 뿐이 안 되기때문에 덜 헷갈리지만, 디렉토리 구조가 복잡해지면 헷갈리기 쉽거든요.

```js
import SearchResult from '../../pages/SearchResult'; // BAD
import SearchResult from '@/pages/SearchResult'; // GOOD
```

2021-07-31 13:46 UTC, cadenzah commented on src/containers/SearchResultContainer.js
> +
불필요한 개행은 제거해주세요. (아래도 마찬가지)

2021-07-31 13:46 UTC, cadenzah commented on src/pages/App.js
> +                <Route exact path="/search-result" component={ SearchResult } />
RESTful한 URL 구조를 생각할 때, `'-'`를 사용해서 URL을 정의하기보다는 [동적 라우팅](https://reactrouter.com/web/api/Hooks/useparams) 또는 [쿼리스트링](https://reactrouter.com/web/example/query-parameters)을 사용하여 URL을 정의하는 것이 더 적절한 것 같습니다.
지금의 경우는 쿼리스트링이 더 적절하겠네요.

예를 들어, `/search?keyword='제주도'` 와 같은 URL 형식인 것이죠. 여기서 쿼리스트링은 ? 이후의 문자열입니다.

2021-07-31 13:46 UTC, cadenzah commented on src/pages/SearchResult.js
> +            <SearchResultContainer />
디자인 시안에 따르면 검색 결과 페이지에서 사용되는 검색 바는, 기존에 검색 홈 페이지에서 사용되는 검색 바가 고스란히 사용되는 형태라고 볼 수 있을 것 같은데요.
그렇다면 문맥으로 보나 기능으로 보나 검색 결과를 보여주는 (SearchResult) 것과는 별개이기 때문에, 두개를 분리하여 컨테이너를 정의하는 것이 더 적절한 것 같습니다.

```js
return (
    <>
        <SearchBarContainer />
        <SearchResultContainer />
    </>
)
```

이렇게 하면, 두 요소에 대한 상태 관리 로직 등을 독립적으로 작성하고 관리할 수 있으니, 유지보수하기에도 더 좋을 듯 하고요.

2021-07-31 13:57 UTC, cadenzah commented
@SEOJIN-LEE 서진님, 지금까지 구현해주신 코드를 가볍게 리뷰해보았는데요, 하나씩 한번 읽어보시고 작업 다시 한번 해보셔요~ ㅎㅎ
참고로, 우리 프로젝트의 디렉토리를 구성해놓은 패턴 또는 구조는 아래를 기반으로 합니다.

- `pages/`: 라우팅 구조에 따라 각 주소 별 최초로 사용되는 컴포넌트
  - 여러 container가 조합되어 사용될 수 있다
  - 페이지 라우팅과 관련된 값들이 여기서 주입된다
  - 스타일 X
- `containers/`: 상태, 네트워크 로직 등이 정의되는 컴포넌트
  - 각종 리덕스, 훅 등이 선언 및 사용될 수 있다
  - 여러 component들을 사용한다
  - 스타일 X (여러 컨테이너들을 동시에 조작하고자 한다면, `components/templates`를 사용하여 레이아웃 구성)
- `components/`: page와 container에서 정의된 데이터(들)을 `props`로 전달받아 이를 바탕으로 실제 화면을 그리는 컴포넌트
  - 스타일을 여기서 구체적으로 부여
  - `common/`: 공통적으로 재사용될 수 있는 컴포넌트
  - `templates/`: 화면 레이아웃을 담당하는 컴포넌트
  - 그 외...

위와 같은 구조가 절대적인 건 아니지만, 특정 용도나 패턴에 따른 위계에 맞추어 파일들을 구성/배치해놓으면
각 코드의 역할과 쓰임을 이해하기 더 용이하고, 따라서 코드를 이해하는 데에 걸리는 시간도 아낄 수 있으니
코드를 작성할 때, 지금 쓰는 코드의 역할이 무엇인지를 고민해보면서 구조를 그려보면 코드 짜기 훨씬 수월할거에요.
서진님 코드를 보니, 전체적인 구조는 어느정도 알고 계신 듯 하고, 제가 적어놓은 코드들도 적절히 잘 파악하고 계신 듯 하네요. 고생하셨어요~~ㅎㅎ

이것저것 말이 많아졌는데, 차분하게 읽어보고 작업 다시 해보셔용~ 화이팅 화이팅

2021-07-31 17:47 UTC, SEOJIN-LEE commented on src/components/SearchResult/ResultItem/ResultItem.js
> +import { FaRegHeart } from "react-icons/fa"; // 빈 하트
맞습니다..!! 지금 1. 찜 icon 집어넣기, 2. UI 참조해서 적절한 위치에 배분하기 작업 진행 중입니다!
로고에 뒤로가기 추가, /search-page 검색시 페이지 나오게 하기, 사진 집어넣기, 사진과 설명 제 위치에 배치하기... 정도가 남은 것 같아요!

2021-07-31 17:58 UTC, SEOJIN-LEE commented on src/components/SearchResult/store.js
> +class SearchResult {
앗,..! 모듈 폴더가 있는 줄 몰랐네요!ㅠㅠ 조금 더 꼼꼼히 볼 걸 그랬나봐요. 이동시킨 후에 말씀하신 사항에 맞춰 수정하겠습니다ㅎㅎㅎ

2021-07-31 17:59 UTC, SEOJIN-LEE commented on src/components/SearchResult/SearchBar/SearchBar.scoped.scss
> +  /* Rectangle 70 */
넵!! 저 부분은 우선 붙여 넣어둔 다음에 차근차근 수정하려고 했어요!

2021-07-31 18:00 UTC, SEOJIN-LEE commented on src/components/SearchResult/SearchBar/SearchBar.scoped.scss
> +  position: absolute;
알겠습니다!!! 자세히 설명하고 알려주셔서 감사합니다 😊

2021-07-31 18:09 UTC, SEOJIN-LEE commented on src/components/SearchResult/ResultList/ResultList.js
> +import * as store from '@/components/SearchResult/store';
넵! 그러면 `<ResultList />`에서  전달받는 `props`는 `resultItemList` object가 되는 게 맞을까요?

2021-07-31 18:15 UTC, SEOJIN-LEE commented on src/components/SearchResult/ResultList/ResultList.js
> +    const [resultItemList, setResultItemList] = useState([]);
이 부분은 프로젝트에 대한 이해도 + 리액트에 대한 지식이 부족해서 생긴 문제 같습니다.. 판매하기를 통해 글이 새로 올라오거나 올렸던 글을 삭제하여 업데이트가 발생하면 ResultList에도 반영돼야 한다고 생각하면서 저렇게 코드를 작성했는데요, 제가 어떤 부분을 잘못 생각한 걸까요?

2021-07-31 18:23 UTC, SEOJIN-LEE commented on src/components/SearchResult/ResultList/ResultList.js
> +    }, [refresh])
감사합니다!! 하지만 스토어 데이터는... 계속해서 바뀌겠죠??

2021-07-31 18:24 UTC, SEOJIN-LEE commented on src/components/SearchResult/index.js
> +export default SearchResult;
아! 안 그래도 삭제를 해놨는데, `commit and push`를 안 했었네요. 반영하겠습니다!

2021-07-31 18:28 UTC, SEOJIN-LEE commented on src/components/SearchResult/index.js
> +import SearchResult from '../../pages/SearchResult';
네! 설명 감사합니다😊 이 부분은 원래 `./SearchResult`였는데, `SearchResult.js`를 `pages`로 옮기면서 자동으로 변환이 된 것 같아요. 아마 그 외 부분은 `@`를 사용하여 작성했을 거예요!! 동일 폴더에 있는 파일을 제외하고는 전부 `@`를 사용하여 작성하면 될까요?

2021-07-31 18:31 UTC, SEOJIN-LEE commented on src/containers/SearchResultContainer.js
> +
가독성 측면에서 개행을 하는 게 낫다고 생각했는데, 불필요한 개행이었군요...!! 바로 수정했습니다! 이렇게 또 하나 배워가네요😄

2021-07-31 18:48 UTC, SEOJIN-LEE commented on src/pages/App.js
> +                <Route exact path="/search-result" component={ SearchResult } />
그렇군요!! 말씀 들으니 저도 쿼리스트링이 더 적절하다고 생각되네요. 참고하여 수정하겠습니다! 링크로 걸어주신 사이트는 리액트에 관해 코드를 보며 공부할 수 있는 사이트인가요?

2021-07-31 18:53 UTC, SEOJIN-LEE commented on src/pages/SearchResult.js
> +            <SearchResultContainer />
넵넵 알겠습니다! 좋은 팁 감사합니다! 정모님 말씀대로 하면 정말 유지보수가 쉬워질 것 같아요. 제가 여태까지 얼마나 마구잡이로 프로젝트를 해왔는지도 깨달을 수 있었습니다. 😢 그럼 SearchBar 역시 SearchResult 폴더에 만드는 게 아니라 common에 넣으면 좋겠네요!

2021-08-01 02:27 UTC, cadenzah commented
@SEOJIN-LEE 서진님, 어제 리뷰 드린거에서 몇가지 더 공유드리면 좋을 내용이 있어 추가로 적어봅니다.

#### 1. 개별 컴포넌트 관련 폴더 이외에는 소문자로 이름 시작

구현해주신 `SearchResult` 폴더 아래에 List, Item 등이 하위 컴포넌트로 들어있는 형식의 구조인데요,

```
- SearchResult
|- ResultItem
|- ResultList
|- SearchBar
```

React에서는 일반적으로 컴포넌트에 대하여서만 PascalCase로 표기하는 것이 컨벤션입니다. 그래서 `SearchResult` 폴더의 경우 컴포넌트가 아니니, 소문자로 작성하는 것이 적절할 것 같습니다. 또한 향후 확장하기 좋도록 단지 검색 결과만이 아닌, 검색 관련 컴포넌트를 모두 포함한다는 의미에서 `search`로 이름짓는 것이 좋을 것 같습니다.

#### 2. 공용 컴포넌트를 사용하는 구조

구현해주신 `SearchResult` 디렉토리에 보면, `<ResultItem>`, `<ResultList>` 등을 사용하여 리스트를 구현하려고 하신 것을 알 수 있었는데요. 그런데 이 요소의 경우, 단지 검색뿐 아니라 다른 상황에서도 충분히 사용될 수 있는, 재사용성이 높은 컴포넌트입니다. 예를 들어, **앱 홈에서 현재 할인중인 상품을 목록으로 표시할 때** 를 들 수가 있겠네요.

그런 맥락에서 볼 때, `SearchResult` 아래에 해당 요소들을 정의하는 것이 아니라 `common` 아래에 공용 컴포넌트로서 리스트 관련 컴포넌트들을 정의하고, `<SearchResultContainer>`에서 해당 공용 컴포넌트들을 사용하는 것이 어떨까 합니다. 그러면 나중에 다른 페이지나 컨테이너에서 리스트형 UI가 필요하게 되더라도 쉽게 활용할 수 있을 것 같아요.

이러한 패턴의 예시는 `common/` 아래에 정의된 다른 컴포넌트들을 한번 참고해보시고, 각 컴포넌트들이 실제 컨테이너에서 어떤 식으로 import 되어서 사용되고 있는지를 확인해보시면 응용에 도움이 될 것 같습니다.

2021-08-01 02:30 UTC, cadenzah commented on src/pages/SearchResult.js
> +            <SearchResultContainer />
`<SearchBar>`가 과연 재사용성이 있는 공용으로 봐야할지? 이건 저도 조금 고민이 됩니다. 과연 다른 상황에 또 필요할까... `SearchBar`는 그냥 검색 페이지에 한정된 컴포넌트로 작성해도 무방할 듯 합니다.

어떤 컴포넌트를 `common/` 아래에 공용으로서 정의하고, 어떤건 특정 페이지 문맥으로 한정할지에 관련된 내용을 아래 댓글에 적어보았으니 한번 확인해보셔요.

2021-08-01 02:31 UTC, cadenzah commented on src/pages/App.js
> +                <Route exact path="/search-result" component={ SearchResult } />
링크해드린 사이트는 React Router 공식 도큐먼트에요. 다른 일반적인 사이트랑 글 적어놓은 형식이 좀 많이 달라서 처음에 잘 안읽히긴 하는데... 구글에 검색해보면 리액트 라우터 관련 글이 많긴 하니, 아무거나 잡히는 거 읽으셔도 무방할 것 같습니다.

2021-08-01 02:32 UTC, cadenzah commented on src/components/SearchResult/index.js
> +import SearchResult from '../../pages/SearchResult';
네 맞아요. 특별한 규칙은 없었는데, 상대 경로 중첩 2개 이상부터는 `@`를 사용하도록 하죠.
참고로 `alias`는 지금 `@` 이외에도 더 정의가 가능하니까, 나중에 필요하면 또 추가하도록 하죠 (아마 안필요할듯)

2021-08-01 03:15 UTC, cadenzah commented on src/components/SearchResult/ResultList/ResultList.js
> +    const [resultItemList, setResultItemList] = useState([]);
여기서 언급한 *값이 수정되는 경우가 없다*라는건, 바로 위 코멘트에 단 내용의 연장선인데, 상위에서 전`props`를 통하여 전달된 데이터를 그대로 사용하기만 하는 상황이라면, 그 데이터를 전달받는 하위 컴포넌트 입장에서는 단지 **화면을 렌더링하는 데에만** 신경쓰면 그만이기 때문에, 그런 맥락에서 데이터는 바뀌지 않는다고 말한 거에요. (엄밀히 보면 틀린 내용이 몇개 들어있지만 이해의 편의를 위하여 넘어가겠습니다).

적어주신 새 글의 추가/수정/제거 등으로 데이터가 갱신되는 상황은 `<ResultList>`가 아니라 그 상위 컨테이너에서 신경써야 하는 로직이라는 말씀입니다.

2021-08-01 03:16 UTC, cadenzah commented on src/components/SearchResult/ResultList/ResultList.js
> +import * as store from '@/components/SearchResult/store';
배열을 쓰면 될 것 같아요.

2021-08-01 03:17 UTC, cadenzah commented on src/components/SearchResult/ResultList/ResultList.js
> +    }, [refresh])
음 어제 이 `useEffect` 로직 부분을 제대로 확인하지 않았던 것 같네요. 나중에 이거 코드 완성하셨을 때 제대로 돌아가는지 꼭 체크해보셔요ㅋㅋ

2021-08-01 03:19 UTC, cadenzah commented on src/components/SearchResult/SearchBar/SearchBar.scoped.scss
> +  position: absolute;
FYI, 검색 메인 화면에서 사용되는 검색 필터 모달을 오전에 구현했어요.
시안에 따르면 검색 필터 모달과 검색 바의 가로 길이가 동일하니, 모달 구현된 것을 참고하여 검색 바 스타일 부여하면 될 것 같네요.

2021-08-01 06:56 UTC, SEOJIN-LEE commented on src/pages/SearchResult.js
> +            <SearchResultContainer />
저도 SearchResult 폴더가 search 폴더로 변경됨에 따라 SearchBar 역시 원래대로 search 폴더에 두는 게 맞다는 생각이 들어요. 원래 common으로 옮겨야겠다고 생각한 이유는 검색 결과 화면 외에 검색 홈 화면에도 재사용돼서였거든요.

2021-08-01 07:14 UTC, SEOJIN-LEE commented on src/components/SearchResult/ResultList/ResultList.js
> +    const [resultItemList, setResultItemList] = useState([]);
아하 ㅎㅎ 이해했습니다. 감사합니다! 상위 컨테이너를 배제하고 생각해서 이해가 잘 되지 않았던 것 같네요.

2021-08-03 10:21 UTC, cadenzah requested changes

2021-08-03 10:21 UTC, cadenzah commented on src/redux/modules/index.js
> +import reducer from './store'
옮겨주신 `store.js`는 검색 쪽 관련된 리덕스 스토어이니, 파일명을 `search.js`로 변경해주세요. 그래야 향후 다른 스토어 추가했을 때 용도 구분을 명확히 할 수 있을 것 같습니다.
import 할 때에도 마찬가지로 용도가 드러나도록 이름을 지어주세요.

2021-08-03 10:21 UTC, cadenzah commented on src/redux/modules/store.js
> +
Redux Toolkit을 사용하여 스토어를 구성하면 더 좋을 것 같지만, 시간 관계상 지금은 우선 넘어가도록 하죠.
이후에 `module/app.js`의 코드 작성 패턴을 보고 수정해주세요.

2021-08-03 10:23 UTC, SEOJIN-LEE commented on src/redux/modules/index.js
> +import reducer from './store'
넵!! 기능별로 store를 만드는 게 처음이라.. 이름을 어떻게 해야할지 모르겠었는데 search로 변경하겠습니다! ㅎㅎ import 이름도요!

2021-08-03 10:24 UTC, cadenzah approved these changes
LGTM

2021-08-03 10:28 UTC, merged